all:
  vars:
    ansible_become: true

    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-1-167.ec2.internal:
      ansible_host: ec2-3-88-91-107.compute-1.amazonaws.com
    ip-10-0-1-246.ec2.internal:
      ansible_host: ec2-18-232-175-212.compute-1.amazonaws.com
    ip-10-0-1-82.ec2.internal:
      ansible_host: ec2-184-72-200-143.compute-1.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-1-72.ec2.internal:
      ansible_host: ec2-54-91-162-162.compute-1.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-91-162-162.compute-1.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-91-162-162.compute-1.amazonaws.com
    ip-10-0-1-213.ec2.internal:
      ansible_host: ec2-23-22-167-85.compute-1.amazonaws.com
      mds_advertised_listener_hostname: ec2-23-22-167-85.compute-1.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-23-22-167-85.compute-1.amazonaws.com
    ip-10-0-1-67.ec2.internal:
      ansible_host: ec2-18-232-150-148.compute-1.amazonaws.com
      mds_advertised_listener_hostname: ec2-18-232-150-148.compute-1.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-18-232-150-148.compute-1.amazonaws.com

schema_registry:
  hosts:
    ip-10-0-1-54.ec2.internal:
      ansible_host: ec2-3-88-182-46.compute-1.amazonaws.com

kafka_rest:
  hosts:
    ip-10-0-1-171.ec2.internal:
      ansible_host: ec2-18-207-168-140.compute-1.amazonaws.com

kafka_connect:
  hosts:
    ip-10-0-1-174.ec2.internal:
      ansible_host: ec2-3-90-27-142.compute-1.amazonaws.com

ksql:
  hosts:
    ip-10-0-1-179.ec2.internal:
      ansible_host: ec2-184-72-172-33.compute-1.amazonaws.com

control_center:
  hosts:
    ip-10-0-1-109.ec2.internal:
      ansible_host: ec2-34-229-80-245.compute-1.amazonaws.com

