all:
  vars:
    ansible_become: true

    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-1-150.ec2.internal:
      ansible_host: ec2-54-226-236-6.compute-1.amazonaws.com
    ip-10-0-1-195.ec2.internal:
      ansible_host: ec2-3-93-189-248.compute-1.amazonaws.com
    ip-10-0-1-154.ec2.internal:
      ansible_host: ec2-52-201-51-89.compute-1.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-1-174.ec2.internal:
      ansible_host: ec2-3-94-166-212.compute-1.amazonaws.com
      mds_advertised_listener_hostname: ec2-3-94-166-212.compute-1.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-3-94-166-212.compute-1.amazonaws.com
    ip-10-0-1-101.ec2.internal:
      ansible_host: ec2-52-87-171-235.compute-1.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-87-171-235.compute-1.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-87-171-235.compute-1.amazonaws.com
    ip-10-0-1-17.ec2.internal:
      ansible_host: ec2-3-88-101-204.compute-1.amazonaws.com
      mds_advertised_listener_hostname: ec2-3-88-101-204.compute-1.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-3-88-101-204.compute-1.amazonaws.com

schema_registry:
  hosts:
    ip-10-0-1-82.ec2.internal:
      ansible_host: ec2-75-101-235-210.compute-1.amazonaws.com

kafka_rest:
  hosts:
    ip-10-0-1-206.ec2.internal:
      ansible_host: ec2-34-235-154-181.compute-1.amazonaws.com

kafka_connect:
  hosts:
    ip-10-0-1-156.ec2.internal:
      ansible_host: ec2-54-196-202-143.compute-1.amazonaws.com

ksql:
  hosts:
    ip-10-0-1-92.ec2.internal:
      ansible_host: ec2-54-174-222-7.compute-1.amazonaws.com

control_center:
  hosts:
    ip-10-0-1-86.ec2.internal:
      ansible_host: ec2-34-236-157-70.compute-1.amazonaws.com

